swagger: '2.0'
info:
  description: 'This is the Jokes API description'
  version: 1.0.0
  title: Swagger JokesApi
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: official-joke-api.appspot.com
schemes:
  - https
paths:
  /random_joke:
    get:
      summary: 'Get a random joke'
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/JokeModel'
        '400':
          description: Invalid status value
definitions:
  JokeModel:
    type: object
    properties:
      id:
        type: integer
        format: int64
      setup:
        type: string
      punchline:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'